const FAMILIY_REQUEST_STATUS = {
    WAITING_VERIFICATION: 10,
    VERIFIED: 20
};

const FAMILIY_CONDITION_STATUS = {
    NO_CONDIITION: 10,
    OKAY: 20,
    NOT_OKAY: 30
};

module.exports = {
    FAMILIY_REQUEST_STATUS,
    FAMILIY_CONDITION_STATUS
};
